const booleanColumnsTrue = [
  'recebe_push_noti',
  'acesso_academia',
  'app_utiliza',
  'app_cadastra_residente',
  'app_edita_residente',
  'app_cadastra_veiculo',
  'app_edita_veiculo',
  'app_cadastra_pet',
  'app_edita_pet',
  'permitido_grupo_pessoas',
  'permitido_bicileta',
  'autorizado_facial',
  'autorizado_qr',
  'requer_revista',
  'liberado',
  'controle_letra_a',
  'controle_letra_b',
  'controle_letra_c',
  'controle_letra_d',
  'notifica',
  'controla_vagas',
  'libera_residente',
  'libera_visitante',
  'pre_lib',
  'libera_residente_cartao',
  'libera_residente_teclado',
  'libera_residente_biometria',
  'libera_visitante_cartao',
  'libera_visitante_teclado',
  'libera_visitante_biometria',
  'catraca',
  'cofre',
  'aviso_sonoro',
  'botoeira',
  'tag_veicular',
  'expedidor',
  'bloqueia_inadimplentes',
  'interno',
  'facial_criancas',
  'academia',
  'horario_comercial',
  'controla_antecedente',
  'seg',
  'ter',
  'qua',
  'qui',
  'sex',
  'sab',
  'dom',
];

const booleanColumnsFalse = [
  'ativo',
];

module.exports = { booleanColumnsTrue, booleanColumnsFalse };